### ISSUE TITLE
Feedback on testing 2023-02-09

### ISSUE THREAD

**Issue by rafahu** [adfinis/timed-frontend#800]
- **Tab function**
1) In tracking > Timesheet: I usual am able to use tab to select an item which was highlighted. It would selected it and go to the next field. Now when I click tab it brings me to the comment field without selecting what I was on.
2) In Analysis > right side bar: same as above
3) In Projects: same as above

- **Reject feature**
1) In Analysis > State: I don't really like that "rejected" is on top. I don't think it will be the most frequently used parameter. In the way I used Timed (and I'm only speaking for myself) I use Billability and Verfied in the fast majority of cases. the others not so much.
2) In Analysis: I went to verify entries I created, I was able to verify, but wasn't able to reject anything (it was always grayed out)

- **Remaining effort feature**: I tested with 10 entries and while the duration kept updating at each new entry, the remaining effort stayed stuck on 30 (regardless if the new effort was above or below)
![image](https://user-images.githubusercontent.com/113115754/217798920-63886908-2fe0-4d1d-a763-a42de8eaf6bd.png)

![image](https://user-images.githubusercontent.com/113115754/217798972-8d59a7bb-4164-4354-8633-71b1d74a2905.png)

In addition the duration included billable and not billable work. Not sure if that's how it should be or not.

- **Budget check timed bot**: couldn't test

Hope this is clear enough.

**Comment by derrabauke** [comment]
Tab function got fixed -> #803

**Comment by derrabauke** [comment]
> Remaining effort feature: I tested with 10 entries and while the duration kept updating at each new entry, the remaining effort stayed stuck on 30 (regardless if the new effort was above or below)

Should be fixed by now. Please check again tomorrow on the test system. We will do a deployment today.

**Comment by rafahu** [comment]
Hi @derrabauke 

- **Tab function**: I'm in the system now and still experience the still issue with the tab function not working... (happy to jump on a call to show you what I mean)

- **estimation**: no improvement noticed... While entering several entries in a row to the same tasks, the hours add up (so it's the proof that the entry is recorded) but hours stay stuck on the 1st new estimation I made... is it 1 per day only? what's the behavior you implemented. Is the expectation that nobody would update the estimation several times? (I would need to check tomorrow if a new estimation is taken into account)
![image](https://user-images.githubusercontent.com/113115754/219300951-6d853aaa-93a8-4cc5-8248-ab8d2a7bf7a8.png)

![image](https://user-images.githubusercontent.com/113115754/219301449-412a6b11-5ef0-4414-97e5-87f891420788.png)

**Comment by derrabauke** [comment]
@rafahu Let's have a call regarding those two points and share the outcomes back to this issue. ;-)
